feat: agave 3.0 dependency upgrades, ci fixes, version bumps, changelog (#624)
* feat: agave 3.0 dependency upgrades, ci fixes, version bumps, changelog

Signed-off-by: GitHub <noreply@github.com>

* refactor: fix typo

Signed-off-by: GitHub <noreply@github.com>

* refactor: cargo fmt

Signed-off-by: GitHub <noreply@github.com>

* worksace: remove dependency pinning ref PR #629

Signed-off-by: GitHub <noreply@github.com>

* feat: remove the incorrect `message_hash` field from protoc

Signed-off-by: GitHub <noreply@github.com>

* refactor: add leftover files from `message_hash` removal

Signed-off-by: GitHub <noreply@github.com>

* refactor: ubuntu-24.04 builds in ci

Signed-off-by: GitHub <noreply@github.com>

* refactor: affinity tests to adjust to the cores available on test GitHub runners

Signed-off-by: GitHub <noreply@github.com>

* refactor: install wasm dependencies in makefile and ci

Signed-off-by: GitHub <noreply@github.com>

---------

Signed-off-by: GitHub <noreply@github.com>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -73,6 +73,13 @@ jobs:
         run: |
           sudo apt-get update
           sudo apt-get install -y libsasl2-dev protobuf-compiler
+          if ! command -v wasm-bindgen-cli &> /dev/null
+          then
+              echo "wasm-bindgen-cli not found, installing"
+              cargo install wasm-bindgen-cli --force
+          else
+              echo "wasm-bindgen-cli is already installed"
+          fi
 
       - name: cargo tree
         run: |
@@ -98,13 +105,13 @@ jobs:
           cargo +nightly fmt --all -- --check
 
       - name: cargo deny check advisories
-        uses: EmbarkStudios/cargo-deny-action@v2.0.1
+        uses: EmbarkStudios/cargo-deny-action@v2.0.13
         with:
           command: check advisories
           rust-version: ${{ env.RUST_STABLE }}
 
       - name: cargo deny check advisories wasm
-        uses: EmbarkStudios/cargo-deny-action@v2.0.1
+        uses: EmbarkStudios/cargo-deny-action@v2.0.13
         with:
           command: check advisories
           rust-version: ${{ env.RUST_STABLE }}
@@ -113,11 +120,8 @@ jobs:
       - name: cargo clippy
         run: cargo clippy --workspace --all-targets
 
-      # THIS STEP IS BROKEN
-      # - name: cargo clippy wasm
-      #   run: |
-      #     cd yellowstone-grpc-client-nodejs/solana-encoding-wasm
-      #     cargo clippy --target wasm32-unknown-unknown --all-targets
+      - name: cargo clippy wasm
+        run: make solana-encoding-wasm-clippy
 
       - name: check features in `client`
         run: cargo check -p yellowstone-grpc-client --all-targets
@@ -132,6 +136,12 @@ jobs:
 
       - name: cargo test
         run: cargo test --all-features
+
+      - name: install wasm dependencies
+        run: make solana-encoding-wasm-install-dependencies
+
+      - name: make solana-encoding-wasm-build
+        run: make solana-encoding-wasm-build
 
       - name: Build
         run: ./ci/cargo-build-test.sh
